# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_referralinvite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set([('campaign', 'referrer')]),
        ),
        migrations.AlterUniqueTogether(
            name='referralinvite',
            unique_together=set([('referral', 'email')]),
        ),
    ]
