# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20170911_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='reward',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='referralinvite',
            unique_together=set([]),
        ),
    ]
