# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20170918_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='button_color',
            field=models.CharField(default='#337ab7', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tagline_color',
            field=models.CharField(default='#666666', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='title_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='top_bar_color',
            field=models.CharField(default='#f8f8f8', max_length=7),
        ),
    ]
