# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20170918_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
