# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaign_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='success_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
