# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20170920_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tagline_color',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title_color',
        ),
    ]
