# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20170920_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='success_url',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='signup_success_url',
            field=models.URLField(blank=True, help_text='Url where user ends up after signing up (used for conversion)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='signup_url',
            field=models.URLField(blank=True, help_text='Url where referrals are led to'),
        ),
    ]
