# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20170920_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.Referral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
