# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_referralsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='signup_success_host',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
