# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_campaign_signup_success_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsignup',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Referral'),
        ),
    ]
