# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20170922_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsignup',
            name='followed_up',
            field=models.BooleanField(default=False),
        ),
    ]
