# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_referralsignup_followed_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralsignup',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
